In [1]:
import numpy as np

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [28]:
a1 = np.zeros((5,4))
a2 = np.ones((5,4))

# swaping through unpacking
a2[[0,3],:], a1[[0,3],:] = a1[[0,3],:], a2[[0,3],:]

print(a1,"\n\n")
print(a2)

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]] 


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [34]:
a = np.arange(1,11)
print(a)

#sliding averages over array a
print(np.cumsum(a))



[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  6 10 15 21 28 36 45 55]
